# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7dae174d87a7d96832a71c794f5c0499a18532b604c8d99f5c11185251c560990a877ddd33e726cde2ebdb9bee88bb8d49465b211204582ebdac3ac8c999e170

test:
  secret_key_base: 6f60814401d7109381c9cd2e701671fb96e04a7f268eb0e27b84a4c331aacf049ee8faf0b39356a9359057c234e0e4416102e20d1fd63c506d08835793893901

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
